import Head from "next/head";
import Header from '@/components/common/Header';
import HeroSection from "@/components/Home";
import About from "@/components/about";
import Education from "@/components/education";
import Experience from "@/components/experience";
import Projects from "@/components/projects";
import Contact from "@/components/contact";
import Tools from "@/components/tools";



export default function Home() {
  return (
    <>
      <Head>
        <Header/>
        <title>Portfolio</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
    <div>
    <HeroSection/>
    <About/>
    <Projects/>
    <Experience/>
    <Tools/>
    <Education/>
    <Contact/>
    </div>
       
    </>
  );
}
